# Generated by Django 4.2.4 on 2023-12-26 19:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('email_address', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('date_brd', django_jalali.db.models.jDateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('poster_photo', models.ImageField(upload_to='post_images/')),
                ('preview_text', models.CharField(default='متن پیش فرض خود را وارد کنید', max_length=130)),
                ('body', ckeditor.fields.RichTextField()),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('published_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=255)),
                ('text', models.TextField()),
                ('email', models.EmailField(default='emailaddress@gmail.com', max_length=254)),
                ('created_time', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Posts.post')),
            ],
        ),
    ]
