# Generated by Django 4.2.4 on 2023-12-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_cooperationrequest_date_brd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_time',
        ),
    ]
